"use client";

import { ArrowLeft, Sparkles, Download, Globe, Play, Volume2, Maximize } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

export default function LessonPage() {
  const params = useParams();
  const id = params.id as string;

  // Let's deduce some title based on id or just a default one
  const titles: Record<string, string> = {
    plants: "How do plants eat?",
    fractions: "Fractions with Pizza",
    pyramids: "Who built the pyramids?",
    dinosaurs: "Dinosaurs!",
    airplanes: "How airplanes fly",
    "solar-system": "The Solar System",
    new: "Your New Custom Lesson",
  };

  const title = titles[id] || "How Rain is Made 🌧️";

  return (
    <div className="min-h-screen bg-[#F5F3FF] flex flex-col">
      {/* Top Navbar for Lesson view */}
      <nav className="p-4 md:p-6">
        <div className="max-w-7xl mx-auto flex justify-between items-center clay-card px-4 md:px-6 py-3 bg-white/80 backdrop-blur-sm">
          <Link
            href="/dashboard"
            className="flex items-center gap-2 text-slate-500 hover:text-indigo-600 font-bold transition-colors"
          >
            <ArrowLeft className="w-5 h-5 shrink-0" />{" "}
            <span className="hidden md:inline">Back to Dashboard</span>
          </Link>

          <div className="flex items-center gap-2 md:gap-3">
            <div className="w-8 h-8 md:w-10 md:h-10 bg-indigo-100 rounded-xl flex items-center justify-center border-2 border-indigo-200">
              <Sparkles className="text-indigo-500 w-4 h-4 md:w-5 md:h-5 shrink-0" />
            </div>
            <h1 className="text-lg md:text-xl font-bold text-indigo-900 tracking-wide hidden sm:block">
              EduAI
            </h1>
          </div>

          <div className="flex gap-2 md:gap-3">
            <button className="clay-btn-secondary px-3 md:px-4 py-2 flex items-center gap-2 text-sm">
              <Download className="w-4 h-4 shrink-0" />{" "}
              <span className="hidden md:inline">MP4</span>
            </button>
            <button className="clay-btn-cta px-3 md:px-4 py-2 flex items-center gap-2 text-sm">
              <Globe className="w-4 h-4 shrink-0" />{" "}
              <span className="hidden md:inline">Share</span>
            </button>
          </div>
        </div>
      </nav>

      <main className="flex-grow flex flex-col justify-center p-4 md:p-6 max-w-7xl mx-auto w-full">
        <div className="w-full max-w-5xl space-y-4 md:space-y-6">
          <div className="text-center mt-2 md:mt-0">
            <h2 className="text-2xl md:text-4xl font-bold text-indigo-900 mb-1 md:mb-2">
              {title}
            </h2>
            <p className="text-sm md:text-base text-slate-500 font-comic">Generated by AI Teacher</p>
          </div>

          {/* The School Board Wrapper */}
          <div className="clay-blackboard aspect-video w-full flex flex-col items-center justify-center p-4 md:p-8 relative overflow-hidden group border-4 md:border-8 border-amber-900/80 shadow-2xl rounded-sm">
            {/* Frame effects */}
            <div className="absolute inset-0 border-4 border-slate-700 pointer-events-none rounded-sm"></div>

            {/* Chalk dust texture on board */}
            <div
              className="absolute inset-0 opacity-10 pointer-events-none"
              style={{
                backgroundImage:
                  "url('data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.65%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22/%3E%3C/svg%3E')",
              }}
            ></div>

            {/* Play button overlay */}
            <div className="absolute inset-0 bg-slate-900/20 flex items-center justify-center opacity-100 hover:opacity-0 transition-opacity z-10 cursor-pointer">
              <button className="w-24 h-24 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center hover:bg-white/30 transition-colors border-4 border-white/50">
                <Play className="w-12 h-12 text-white ml-2" />
              </button>
            </div>

            {/* Lesson Content (Animated SVG) */}
            <svg
              className="w-full h-full opacity-90 relative z-0"
              viewBox="0 0 400 200"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M100 150 Q 150 100 200 150 T 300 150"
                stroke="#60A5FA"
                strokeWidth="4"
                fill="none"
                strokeDasharray="10,5"
                className="animate-pulse"
              />
              <circle cx="100" cy="150" r="10" fill="#3B82F6" />
              <circle cx="200" cy="150" r="10" fill="#3B82F6" />
              <circle cx="300" cy="150" r="10" fill="#3B82F6" />
              <text
                x="100"
                y="180"
                fontFamily="'Comic Neue', cursive"
                fontSize="14"
                fill="#E2E8F0"
                textAnchor="middle"
              >
                Evaporation
              </text>
              <text
                x="200"
                y="180"
                fontFamily="'Comic Neue', cursive"
                fontSize="14"
                fill="#E2E8F0"
                textAnchor="middle"
              >
                Condensation
              </text>
              <text
                x="300"
                y="180"
                fontFamily="'Comic Neue', cursive"
                fontSize="14"
                fill="#E2E8F0"
                textAnchor="middle"
              >
                Precipitation
              </text>
            </svg>
          </div>

          <div className="flex justify-center gap-4 mt-6">
            <button className="clay-btn-secondary w-12 h-12 rounded-full flex items-center justify-center hover:bg-indigo-50">
              <Volume2 className="w-5 h-5 text-slate-600" />
            </button>
            <button className="clay-btn-secondary w-12 h-12 rounded-full flex items-center justify-center hover:bg-indigo-50">
              <Maximize className="w-5 h-5 text-slate-600" />
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
