import { Search, Compass, ArrowRight } from "lucide-react";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { ExploreSection } from "@/components/home/ExploreSection";

export default function Home() {
  return (
    <div className="min-h-screen relative pb-20">
      <Navbar />

      <main className="max-w-7xl mx-auto px-6 mt-4">
        <div className="space-y-12">
          {/* Hero Section */}
          <div className="text-center space-y-6 max-w-3xl mx-auto mt-8">
            <h2 className="text-5xl md:text-6xl font-bold text-indigo-900 leading-tight">
              Magical <span className="text-emerald-500 inline-block animate-float">Animated</span> Lessons!
            </h2>
            <p className="text-xl text-slate-600 font-comic">
              Search and watch fun lessons generated by our AI teacher. Learning has never been this easy!
            </p>

            {/* Search Bar */}
            <div className="relative max-w-xl mx-auto mt-8 group">
              <Search className="absolute left-6 top-1/2 transform -translate-y-1/2 text-slate-400 w-6 h-6 group-focus-within:text-indigo-500 transition-colors" />
              <input
                type="text"
                placeholder="What do you want to learn today? (e.g. How do plants grow?)"
                className="w-full clay-input py-5 pl-16 pr-6 text-lg font-comic placeholder-slate-400"
              />
            </div>
          </div>

          {/* Catalogue Section (Using our new component with custom hook) */}
          <ExploreSection />

          {/* Call to action */}
          <div className="mt-16 bg-indigo-50 rounded-3xl p-10 text-center clay-card border-4 border-indigo-100">
            <h3 className="text-3xl font-bold text-indigo-900 mb-4">Want to create your own lessons?</h3>
            <p className="text-lg text-slate-600 font-comic mb-8">Sign in to ask the AI teacher any question!</p>
            <Link
              href="/dashboard"
              className="clay-btn-cta px-10 py-4 text-xl flex items-center justify-center gap-3 mx-auto w-max no-underline"
            >
              Create Account
              <ArrowRight className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}