"use client";

import { useLessonPlayer } from "@/hooks/useLessonPlayer";
import { Play, Pause, Volume2, VolumeX } from "lucide-react";

interface LessonPlayerProps {
  lessonData: any;
}

export function LessonPlayer({ lessonData }: LessonPlayerProps) {
  const {
    containerRef,
    sceneTitle,
    isStarted,
    isPlaying,
    speechEnabled,
    progress,
    currentTime,
    totalTime,
    currentSceneIdx,
    totalScenes,
    togglePlay,
    toggleSpeech,
    seek,
  } = useLessonPlayer(lessonData);

  if (!lessonData) return null;

  return (
    <div className="w-full max-w-5xl mx-auto space-y-4 md:space-y-6">
      <div className="text-center mt-2 md:mt-0">
        <h2 className="text-2xl md:text-4xl font-bold text-indigo-900 mb-1 md:mb-2">
          {sceneTitle || "Lekcja"}
        </h2>
        <p className="text-sm md:text-base text-slate-500 font-comic">Generated by AI Teacher</p>
      </div>

      {/* Player View */}
      <div className="relative w-full aspect-video rounded-2xl overflow-hidden shadow-2xl border-4 border-slate-200 bg-white">
        {/* SVG Container */}
        <div
          ref={containerRef}
          className="lesson-player-view w-full h-full [&>svg]:w-full [&>svg]:h-full [&>svg]:block"
        />

        {/* Play button overlay */}
        {!isStarted && (
          <div
            className="absolute inset-0 bg-black/30 flex items-center justify-center transition-colors z-30 cursor-pointer"
            onClick={togglePlay}
          >
            <button className="w-20 h-20 md:w-24 md:h-24 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center hover:bg-white/30 transition-all border-4 border-white/50 hover:scale-110">
              <Play className="w-10 h-10 md:w-12 md:h-12 text-white ml-1" />
            </button>
          </div>
        )}
      </div>

      {/* Controls */}
      <div className="flex flex-col gap-3 bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        {/* Playback controls */}
        <div className="flex items-center gap-3">
          <button
            onClick={togglePlay}
            className="clay-btn-cta w-11 h-11 rounded-full flex items-center justify-center shrink-0"
          >
            {isPlaying ? (
              <Pause className="w-5 h-5 text-white" />
            ) : (
              <Play className="w-5 h-5 text-white ml-0.5" />
            )}
          </button>

          <input
            type="range"
            value={progress}
            min="0"
            max="100"
            step="0.1"
            onChange={(e) => seek(Number(e.target.value))}
            className="flex-grow h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-500"
          />

          <span className="text-xs font-mono text-slate-500 w-24 text-right shrink-0">
            {currentTime.toFixed(1)}s / {totalTime.toFixed(1)}s
          </span>

          <button
            onClick={toggleSpeech}
            className={`clay-btn-secondary w-11 h-11 rounded-full flex items-center justify-center shrink-0 ${
              speechEnabled
                ? "bg-indigo-50 text-indigo-600"
                : "bg-slate-100 text-slate-400"
            }`}
          >
            {speechEnabled ? (
              <Volume2 className="w-5 h-5" />
            ) : (
              <VolumeX className="w-5 h-5" />
            )}
          </button>
        </div>

        {/* Scene indicator */}
        <div className="flex justify-center gap-1.5">
          {Array.from({ length: totalScenes }).map((_, i) => (
            <div
              key={i}
              className={`h-1.5 rounded-full transition-all duration-300 ${
                i === currentSceneIdx
                  ? "w-8 bg-indigo-500"
                  : i < currentSceneIdx
                    ? "w-3 bg-indigo-300"
                    : "w-3 bg-slate-200"
              }`}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
